import { Link, useParams } from 'react-router-dom';
import { ArrowLeft, CheckCircle2, Edit3, MapPin, Send, XCircle } from 'lucide-react';
import { warnings } from '../data/warnings';

export default function WarningDetailsPage() {
  const { warningId } = useParams();
  const warning = warnings.find(item => item.id === warningId) || warnings[0];
  return <div className="space-y-6"><Link to="/staff/warnings" className="inline-flex items-center gap-2 text-sm font-bold text-blue-700"><ArrowLeft size={16}/> Back to warnings</Link><div className="flex flex-wrap items-start justify-between gap-4"><div><div className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">Warning details</div><h1 className="mt-2 text-3xl font-black">{warning.id}</h1><p className="mt-1 text-sm text-slate-500">Issued {warning.issuedOn}</p></div><div className="flex gap-2"><button type="button" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-bold"><Edit3 size={15}/> Edit</button><button type="button" className="inline-flex items-center gap-2 rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white"><Send size={15}/> Escalate</button></div></div><div className="grid gap-6 lg:grid-cols-[1.1fr_.9fr]"><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div className="flex items-center justify-between"><h2 className="text-xl font-bold">{warning.title}</h2><span className="rounded-full bg-orange-100 px-3 py-1 text-xs font-bold text-orange-700">{warning.severity}</span></div><dl className="mt-6 grid gap-5 sm:grid-cols-2 text-sm"><div><dt className="text-slate-500">Hazard type</dt><dd className="mt-1 font-bold">{warning.type}</dd></div><div><dt className="text-slate-500">Affected area</dt><dd className="mt-1 font-bold">{warning.area}</dd></div><div><dt className="text-slate-500">Valid from</dt><dd className="mt-1 font-bold">{warning.issuedOn}</dd></div><div><dt className="text-slate-500">Valid until</dt><dd className="mt-1 font-bold">{warning.validUntil}</dd></div><div className="sm:col-span-2"><dt className="text-slate-500">Message</dt><dd className="mt-1 rounded-xl bg-slate-50 p-4 leading-6">{warning.message}</dd></div></dl></section><section className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><h2 className="text-xl font-bold">Affected Area Map</h2><div className="relative mt-4 h-56 rounded-xl bg-[#dcebdc]"><div className="absolute inset-8 rounded-[45%] bg-[#b9d99c]"/><div className="absolute left-1/2 top-1/3 h-16 w-16 rounded-full bg-red-400/80"/><div className="relative z-10 flex h-full items-center justify-center"><MapPin className="text-red-700" size={32}/></div></div><div className="mt-5 grid grid-cols-2 gap-3 text-sm"><div className="rounded-xl bg-emerald-50 p-3"><CheckCircle2 className="text-emerald-600" size={18}/><b className="mt-1 block">Active</b><span className="text-xs text-slate-500">{warning.recipients} recipients</span></div><div className="rounded-xl bg-slate-50 p-3"><XCircle className="text-slate-500" size={18}/><b className="mt-1 block">Audit trail</b><span className="text-xs text-slate-500">8 events recorded</span></div></div></section></div></div>;
}
