import { useMemo } from 'react';
import { Link, useParams } from 'react-router-dom';
import { jsPDF } from 'jspdf';
import { useReportGeneration } from '../context/ReportGenerationContext';
import DataSourceNotice from '../components/DataSourceNotice';
import useMonitoringData from '../hooks/useMonitoringData';
import { reportService } from '../services/reportService';

const reportSections = [
  ['Hazard Warnings', 'alertTimeline'],
  ['Citizens Reached', 'citizensReached'],
  ['Shelter Occupancy', 'shelterOccupancy'],
  ['Resource Distribution', 'resourceDistribution'],
];

function downloadReportPdf(report) {
  const document = new jsPDF();
  const left = 16;
  const width = 178;
  let y = 20;
  const write = (text, options = {}) => {
    const { size = 10, bold = false, gap = 6 } = options;
    document.setFont('helvetica', bold ? 'bold' : 'normal');
    document.setFontSize(size);
    const lines = document.splitTextToSize(String(text ?? ''), width);
    if (y + lines.length * 5 > 280) {
      document.addPage();
      y = 20;
    }
    document.text(lines, left, y);
    y += lines.length * 5 + gap;
  };

  write('DISASTER MANAGEMENT CENTRE', { size: 10, bold: true, gap: 3 });
  write(report.reportType || report.type || 'Disaster Response Report', { size: 19, bold: true, gap: 5 });
  write(`District: ${report.district || 'All Districts'}`);
  write(`Period: ${report.period || `${report.dateFrom || ''} to ${report.dateTo || ''}`}`);
  write(`Generated: ${report.generatedOn || ''}`);
  write(`Generated by: ${report.generatedBy || 'DMC staff'}`, { gap: 10 });

  const selectedSections = new Set(report.selectedSections || []);
  if (report.verifiedReportCount !== undefined) {
    write('Incident Summary', { size: 13, bold: true, gap: 4 });
    write(`Verified hazard reports: ${report.verifiedReportCount}`);
  }
  if (selectedSections.has('Citizens Reached'))
    write(`Total citizens reached: ${Number(report.citizensReachedTotal || 0).toLocaleString()}`);

  reportSections.forEach(([title, key]) => {
    if (!selectedSections.has(title)) return;
    const records = report[key];
    write(title, { size: 13, bold: true, gap: 4 });
    if (!Array.isArray(records) || records.length === 0) {
      write('No operational records matched this district and date range.', { gap: 4 });
      return;
    }
    records.forEach((record, index) => {
      const details = Object.entries(record || {})
        .map(([label, value]) => `${label}: ${typeof value === 'object' ? JSON.stringify(value) : value}`)
        .join(' | ');
      write(`${index + 1}. ${details || 'No details available'}`, { gap: 4 });
    });
  });

  const pageCount = document.getNumberOfPages();
  for (let page = 1; page <= pageCount; page += 1) {
    document.setPage(page);
    document.setFont('helvetica', 'normal');
    document.setFontSize(8);
    document.text(`DMC Statistical Report | Page ${page} of ${pageCount}`, left, 290);
  }

  const filename = `${String(report.reportType || 'disaster-report').toLowerCase().replace(/[^a-z0-9]+/g, '-')}-${report.id || 'export'}.pdf`;
  document.save(filename);
}

export default function ReportDetailsPage() {
  const { reportId } = useParams();
  const { reportResult } = useReportGeneration();
  const cachedReport = useMemo(() => reportResult && reportResult.id === reportId ? reportResult : null, [reportResult, reportId]);
  const { data: loadedReport, loading, error, source, notice } = useMonitoringData(
    () => cachedReport
      ? Promise.resolve({ data: cachedReport, source: 'backend', notice: '' })
      : reportService.getReportById(reportId).then(data => ({ data, source: 'backend', notice: '' })),
    `${reportId}-${cachedReport?.id || 'fetch'}`,
  );
  const report = cachedReport || loadedReport;

  const handleDownloadPdf = () => {
    if (!report) return;
    downloadReportPdf(report);
  };

  if (loading) return <div className="space-y-5"><h1 className="text-3xl font-black text-slate-900">Loading Report…</h1><DataSourceNotice loading={loading} /></div>;

  if (!report) {
    return (
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h1 className="text-3xl font-black text-slate-900">{error ? 'Unable to Load Report' : 'Report Not Found'}</h1>
        <p className="mt-3 text-slate-600">{error || 'This generated report could not be located.'}</p>
        <Link to="/staff/reports/history" className="mt-5 inline-block rounded-xl bg-blue-700 px-4 py-2 text-white">Back to history</Link>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <DataSourceNotice source={source} notice={notice} />
      <div className="flex items-center justify-between">
        <div>
          <div className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">Monitoring & Reports</div>
          <h1 className="mt-2 text-3xl font-black text-slate-900">Report Generated Successfully!</h1>
        </div>
        <div className="flex flex-wrap justify-end gap-2">
          <button type="button" onClick={handleDownloadPdf} className="rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white shadow-sm transition hover:bg-blue-800">Download PDF</button>
          <Link to="/staff/reports/history" className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700">View history</Link>
        </div>
      </div>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,.8fr)]">
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="mb-5 border-b border-slate-200 pb-4">
            <div className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">Disaster Response Report</div>
            <h2 className="mt-2 text-2xl font-black text-slate-900">{report.reportType}</h2>
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Report Type</div><div className="mt-1 font-semibold text-slate-800">{report.reportType || report.type}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Period</div><div className="mt-1 font-semibold text-slate-800">{report.period}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">District(s)</div><div className="mt-1 font-semibold text-slate-800">{report.district}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Generated On</div><div className="mt-1 font-semibold text-slate-800">{report.generatedOn}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Generated By</div><div className="mt-1 font-semibold text-slate-800">{report.generatedBy}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Document</div><div className="mt-1 font-semibold text-slate-800">PDF report ready to download</div></div>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5 shadow-sm">
          <h3 className="text-lg font-bold text-slate-800">Actions</h3>
          <div className="mt-4 space-y-3">
            <button type="button" onClick={handleDownloadPdf} className="w-full rounded-xl bg-blue-700 px-4 py-2 text-sm font-bold text-white shadow-sm transition hover:bg-blue-800">Download PDF</button>
            <button type="button" disabled title="External sharing integration is not configured" className="w-full cursor-not-allowed rounded-xl border border-slate-200 bg-slate-100 px-4 py-2 text-sm font-medium text-slate-500">Share Report · unavailable</button>
            <span className="block w-full rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-2 text-center text-sm font-medium text-emerald-800">Saved to Reports</span>
            <Link to="/staff/reports/generate" className="block w-full rounded-xl border border-slate-200 bg-white px-4 py-2 text-center text-sm font-medium text-slate-700">Generate New Report</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
