import { useMemo } from 'react';
import { Link, useParams } from 'react-router-dom';
import { useReportGeneration } from '../context/ReportGenerationContext';
import { getReportById } from '../utils/monitoringReports';

export default function ReportDetailsPage() {
  const { reportId } = useParams();
  const { reportResult } = useReportGeneration();
  const fallbackReport = useMemo(() => getReportById(reportId), [reportId]);
  const report = reportResult && reportResult.id === reportId ? reportResult : fallbackReport;

  if (!report) {
    return (
      <div className="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
        <h1 className="text-3xl font-black text-slate-900">Report Not Found</h1>
        <p className="mt-3 text-slate-600">This generated report could not be located.</p>
        <Link to="/staff/reports/history" className="mt-5 inline-block rounded-xl bg-blue-700 px-4 py-2 text-white">Back to history</Link>
      </div>
    );
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <div className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">Monitoring & Reports</div>
          <h1 className="mt-2 text-3xl font-black text-slate-900">Report Generated Successfully!</h1>
        </div>
        <Link to="/staff/reports/history" className="rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700">View history</Link>
      </div>

      <div className="grid gap-6 lg:grid-cols-[minmax(0,1.2fr)_minmax(0,.8fr)]">
        <div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm">
          <div className="mb-5 border-b border-slate-200 pb-4">
            <div className="text-xs font-semibold uppercase tracking-[0.18em] text-blue-700">Disaster Response Report</div>
            <h2 className="mt-2 text-2xl font-black text-slate-900">{report.reportType}</h2>
          </div>
          <div className="grid gap-4 md:grid-cols-2">
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Report Type</div><div className="mt-1 font-semibold text-slate-800">{report.reportType}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Period</div><div className="mt-1 font-semibold text-slate-800">{report.period}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">District(s)</div><div className="mt-1 font-semibold text-slate-800">{report.district}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Generated On</div><div className="mt-1 font-semibold text-slate-800">{report.generatedOn}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">Generated By</div><div className="mt-1 font-semibold text-slate-800">{report.generatedBy}</div></div>
            <div><div className="text-xs uppercase tracking-[0.12em] text-slate-500">File Size</div><div className="mt-1 font-semibold text-slate-800">2.4 MB</div></div>
          </div>
        </div>

        <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5 shadow-sm">
          <h3 className="text-lg font-bold text-slate-800">Actions</h3>
          <div className="mt-4 space-y-3">
            <button type="button" className="w-full rounded-xl bg-blue-700 px-4 py-2 text-sm font-medium text-white">Download PDF</button>
            <button type="button" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700">View Report</button>
            <button type="button" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700">Share Report</button>
            <button type="button" className="w-full rounded-xl border border-slate-200 bg-white px-4 py-2 text-sm font-medium text-slate-700">Save to Reports</button>
            <Link to="/staff/reports/generate" className="block w-full rounded-xl border border-slate-200 bg-white px-4 py-2 text-center text-sm font-medium text-slate-700">Generate New Report</Link>
          </div>
        </div>
      </div>
    </div>
  );
}
