import { useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { Button, Field, Header, Screen } from '../../components/UI';
import { useAuth } from '../../context/AuthContext';
import { colors } from '../../theme';

export default function SignupScreen({ navigation }) {
  const { signup } = useAuth(); const [values, setValues] = useState({ name: '', phone: '', email: '', password: '', role: 'CITIZEN' }); const [busy, setBusy] = useState(false);
  const set = key => value => setValues(current => ({ ...current, [key]: value }));
  async function submit() { if (!values.name || !values.phone || !values.email || values.password.length < 6) return Alert.alert('Check your details', 'Enter all details and use a password with at least 6 characters.'); setBusy(true); try { await signup(values); } catch (error) { Alert.alert('Unable to create account', error.message); } finally { setBusy(false); } }
  return <Screen><Header title="Create account" subtitle="Mobile access is available for citizens and community volunteers." /><Field label="Full name" value={values.name} onChangeText={set('name')} /><Field label="Phone number" value={values.phone} onChangeText={set('phone')} keyboardType="phone-pad" /><Field label="Email" value={values.email} onChangeText={set('email')} autoCapitalize="none" keyboardType="email-address" /><Field label="Password" value={values.password} onChangeText={set('password')} secureTextEntry /><Text style={{ fontWeight: '700', color: colors.text, marginBottom: 8 }}>I am registering as</Text><View style={{ flexDirection: 'row', gap: 10 }}><Pressable onPress={() => setValues({ ...values, role: 'CITIZEN' })} style={{ flex: 1, padding: 14, borderRadius: 12, borderWidth: 2, borderColor: values.role === 'CITIZEN' ? colors.primary : colors.border }}><Text style={{ textAlign: 'center', color: colors.text }}>Citizen</Text></Pressable><Pressable onPress={() => setValues({ ...values, role: 'COMMUNITY_VOLUNTEER' })} style={{ flex: 1, padding: 14, borderRadius: 12, borderWidth: 2, borderColor: values.role === 'COMMUNITY_VOLUNTEER' ? colors.primary : colors.border }}><Text style={{ textAlign: 'center', color: colors.text }}>Volunteer</Text></Pressable></View><Button title={busy ? 'Creating...' : 'Create account'} onPress={submit} disabled={busy} /><Pressable onPress={() => navigation.navigate('Login')}><Text style={{ textAlign: 'center', marginTop: 20, color: colors.muted }}>Already registered? <Text style={{ color: colors.primary, fontWeight: '700' }}>Log in</Text></Text></Pressable></Screen>;
}
